export MeetingI = {
    "created_at": "2021-11-27T05:35:31Z",
    "duration": 60,
    "encrypted_password": "dUhDTVZITEF6eDhSM3huREdyZWdBUT09",
    "h323_password": "582902",
    "host_email": "rabihutomo11@gmail.com",
    "host_id": "xctEn3RjRbKuEIgpYaoEDA",
    "id": 79533701329,
    "join_url": "https://us04web.zoom.us/j/79533701329?pwd=dUhDTVZITEF6eDhSM3huREdyZWdBUT09",
    "password": "5ZctTh",
    "pre_schedule": false,
    "pstn_password": "582902",
    "settings": {
        "allow_multiple_devices": false,
        "alternative_hosts": "",
        "alternative_hosts_email_notification": true,
        "approval_type": 2,
        "approved_or_denied_countries_or_regions": {
            "enable": false
        },
        "audio": "voip",
        "auto_recording": "none",
        "breakout_room": {
            "enable": false
        },
        "close_registration": false,
        "cn_meeting": false,
        "device_testing": false,
        "encryption_type": "enhanced_encryption",
        "enforce_login": false,
        "enforce_login_domains": "",
        "focus_mode": false,
        "host_video": false,
        "in_meeting": false,
        "jbh_time": 0,
        "join_before_host": false,
        "meeting_authentication": false,
        "mute_upon_entry": false,
        "participant_video": false,
        "registrants_confirmation_email": true,
        "registrants_email_notification": true,
        "request_permission_to_unmute_participants": false,
        "show_share_button": false,
        "use_pmi": false,
        "waiting_room": true,
        "watermark": false
    },
    "start_time": "2021-11-27T05:35:31Z",
    "start_url": "https://us04web.zoom.us/s/79533701329?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMSIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJhdWQiOiJjbGllbnRzbSIsInVpZCI6InhjdEVuM1JqUmJLdUVJZ3BZYW9FREEiLCJpc3MiOiJ3ZWIiLCJzdHkiOjEsIndjZCI6InVzMDQiLCJjbHQiOjAsIm1udW0iOiI3OTUzMzcwMTMyOSIsInN0ayI6ImNfNEJrcUlyaUpjaU9pTDNZZG5VVkdBTmdBY091aGFqdnpvaDhoSDgyQ1UuQUcuSUNYeUtfeUxSaHZSbUdfZ2l2bU13NEp0ODZUcmljbDBVdVVhNDdFcE5lSXVMV1hvTnVKdzlLLU1pbWRJSDZ6bnlQVE9JVXpkRVFEWmRiZU8ubGdrMF9kWVBSbFVUbS1INXE4LWhPQS5CUHl2ODl0dlFUUXp5aENsIiwiZXhwIjoxNjM3OTk4NTMxLCJpYXQiOjE2Mzc5OTEzMzEsImFpZCI6IkswRXZnS1dQUkVXMEZJZEg4LXhuM2ciLCJjaWQiOiIifQ.INbEXkDc_F-u7CbXuMg801loamigylVIan9oBwXOkpY",
    "status": "waiting",
    "timezone": "Asia/Jakarta",
    "topic": "belajar",
    "type": 2,
    "uuid": "TK5IxKDkRc22nwUolrbJAg=="
}
